# Generated by Django 4.2.8 on 2023-12-29 00:54

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='обновленно в: ')),
                ('working_hours', models.CharField(help_text='Specify the working hours.', max_length=100, verbose_name='Working Hours')),
                ('address_url', models.URLField(blank=True, help_text='URL of the contact address.', null=True, verbose_name='Address URL')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(help_text='Specify the contact email address.', max_length=254, verbose_name='Contact Email')),
                ('telegram_url', models.URLField(blank=True, help_text='URL for Telegram.', null=True, verbose_name='Telegram URL')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
