# Generated by Django 4.2.7 on 2023-12-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано в: ')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='обновленно в: ')),
                ('working_hours', models.CharField(max_length=100, verbose_name='Working Hours')),
                ('contact_address', models.TextField(blank=True, null=True, verbose_name='Contact Address')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
            ],
            options={
                'verbose_name_plural': 'About Us',
            },
        ),
    ]
