# Generated by Django 4.2.7 on 2023-12-21 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='updated_at',
        ),
    ]
