# Generated by Django 4.2.8 on 2023-12-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_recommended',
        ),
        migrations.AddField(
            model_name='product',
            name='is_recommended',
            field=models.ManyToManyField(blank=True, to='product.product'),
        ),
    ]
