# Generated by Django 4.2.8 on 2023-12-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Изображения'),
        ),
    ]
