# Generated by Django 4.2.8 on 2023-12-28 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_is_recommended_product_is_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_recommended',
        ),
        migrations.AddField(
            model_name='product',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
