# Generated by Django 4.2.8 on 2023-12-26 16:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUsMessage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusmessage',
            options={'verbose_name': 'Contact Us Message', 'verbose_name_plural': 'Contact Us Messages'},
        ),
        migrations.AlterField(
            model_name='contactusmessage',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Contact Phone'),
        ),
        migrations.AlterField(
            model_name='contactusmessage',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactusmessage',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='contactusmessage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
