# Generated by Django 4.2.8 on 2023-12-26 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContactUsMessage', '0002_alter_contactusmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactusmessage',
            options={'ordering': ['-id'], 'verbose_name': 'Contact Us Message', 'verbose_name_plural': 'Contact Us Messages'},
        ),
    ]
