# Generated by Django 4.2.8 on 2024-01-09 15:45

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telegram_url', models.URLField(blank=True, help_text='URL для Telegram.', null=True, verbose_name='Ссылка на Telegram')),
                ('instagram_url', models.URLField(blank=True, help_text='URL для Instagram.', null=True, verbose_name='Ссылка на Instagram')),
            ],
        ),
    ]
