# Generated by Django 4.2.8 on 2024-01-04 23:06

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=20, region=None)),
                ('telegram_url', models.URLField(blank=True, help_text='URL for Telegram.', null=True, verbose_name='Telegram URL')),
                ('instagram_url', models.URLField(blank=True, help_text='URL for Instagram.', null=True, verbose_name='Instagram URL')),
            ],
        ),
    ]
